#!/usr/bin/env ruby
# SPDX-License-Identifier: MIT

rplugin_home = ENV["RPLUGIN_HOME"]
rplugin_home = File.expand_path(rplugin_home && !rplugin_home.empty? ? rplugin_home : "~/.rplugin")
if Gem::Version.new(RUBY_VERSION) >= Gem::Version.new("3.3") && File.file?(File.join(rplugin_home, "lib", "rplugin.rb"))
  begin
    require File.join(rplugin_home, "lib", "rplugin")
  rescue LoadError, SyntaxError, StandardError
    nil
  end
end
require_relative "../lib/reach"

exit Plugin.run(ARGV)
